// デフォルト単元データ
// 授業で使う単元を追加・編集してください

// ══ Default units (seeded on first load) ══
const DEFAULTS=[
  {name:'EngComm3 U2R1, 2',words:[
    {en:'contemporary',jp:'現代の'},{en:'calculation',jp:'計算'},{en:'progress',jp:'進歩する'},
    {en:'multiple',jp:'多数の'},{en:'categorize',jp:'…を分類する'},{en:'accurately',jp:'正確に'},
    {en:'outperform',jp:'…よりすぐれている'},{en:'detect',jp:'…を検出する'},{en:'diagnose',jp:'…を診断する'},
    {en:'treatment',jp:'治療法'},{en:'monitor',jp:'…を監視する'},{en:'similarly',jp:'同様に'},
    {en:'crop',jp:'（農）作物'},{en:'productive',jp:'生産性の高い'},{en:'vehicle',jp:'乗り物'},
    {en:'rapidly',jp:'速く'},{en:'awfully',jp:'非常に'},{en:'mechanical',jp:'機械の'},
    {en:'geography',jp:'地理学'},{en:'sorrowfully',jp:'悲しげに'},{en:'county',jp:'郡'},
    {en:'inspector',jp:'調査員，検査官'},{en:'sector',jp:'部門，分野'},{en:'satisfactory',jp:'満足のいく'},
    {en:'superior',jp:'傲慢な，見下すような'},{en:'stupid',jp:'ばか（だな）'},{en:'dispute',jp:'…に反論する'},
    {en:'whistle',jp:'口笛を吹く'},{en:'fraction',jp:'分数'},{en:'sigh',jp:'ため息'},
    {en:'flash',jp:'ぴかっと光る'}
  ]},
  {name:'EngComm3 U1R1, 2',words:[
    {en:'congratulation',jp:'おめでとう'},{en:'frustrated',jp:'ストレスがたまった'},{en:'inevitably',jp:'必然的に'},
    {en:'overwhelm',jp:'…を圧倒する'},{en:'systematic',jp:'系統だった'},{en:'confidence',jp:'自信'},
    {en:'overcome',jp:'…を克服する'},{en:'stretch',jp:'…（の能力）を伸ばす'},{en:'academically',jp:'勉強に関して'},
    {en:'praise',jp:'…をほめる'},{en:'encounter',jp:'…に遭遇する'},{en:'failure',jp:'失敗，不成功'},
    {en:'literature',jp:'文学'},{en:'recall',jp:'…を思い出す'},{en:'implication',jp:'影響'},
    {en:'actively',jp:'積極的に'},{en:'typically',jp:'たいていは'},{en:'previously',jp:'以前に'},
    {en:'odd',jp:'奇妙な'},{en:'cue',jp:'手がかり'},{en:'phrase',jp:'語句'},
    {en:'imagery',jp:'イメージ，心象'},{en:'embarrass',jp:'…を困らせる'},{en:'embarrassed',jp:'当惑した，恥ずかしい'},
    {en:'affectionate',jp:'愛情の込もった'},{en:'effectively',jp:'効果的に'},{en:'despair',jp:'絶望する'},
    {en:'periodic',jp:'定期的な'}
  ]},
  {name:'EngComm3 U1R1 英英',words:[
    {en:'recall',jp:'to think of something from the past'},
    {en:'implication',jp:'a possible outcome of an action or event'},
    {en:'actively',jp:'in an active or positive way'},
    {en:'relate',jp:'to make a connection (between things)'},
    {en:'turtle',jp:'a reptile with a hard round shell that lives in water'},
    {en:'reptile',jp:'a cold-blooded animal, such as a snake or lizard'},
    {en:'cold-blooded',jp:'used for an animal whose body temperature changes to match its environment'},
    {en:'typically',jp:'in a way that something usually happens'},
    {en:'Ebbinghaus forgetting curve',jp:'a curve that shows how memory is lost if no effort is made to retain it'},
    {en:'German',jp:'from or related to Germany'},
    {en:'well-researched',jp:'to have been studied extensively'},
    {en:'short-term',jp:'happening only for a short time'},
    {en:'previously',jp:'before a particular time'},
    {en:'re-read',jp:'to read again'},
    {en:'self-quizzing',jp:'asking yourself questions about what has been studied'},
    {en:'odd',jp:'different or unusual'},
    {en:'cue',jp:'an event or action that is a sign for what will happen'},
    {en:'mnemonic',jp:'associations that help you remember something'},
    {en:'phrase',jp:'words used together to form a meaning'},
    {en:'imagery',jp:'pictures formed in the mind when listening or reading'},
    {en:'commonly',jp:'done by most people'},
    {en:'misspell',jp:'to make a mistake in spelling'},
    {en:'embarrass',jp:'to make someone feel uncomfortable or ashamed, especially in a social situation'},
    {en:'tricky',jp:'difficult or complicated to do'},
    {en:'embarrassed',jp:'the state of feeling uncomfortable or ashamed, especially in front of others'},
    {en:'affectionate',jp:'expressing love and care'},
    {en:'effectively',jp:'in a way that produces the desired result'},
    {en:'despair',jp:'to feel hopeless'},
    {en:'combat',jp:'to fight against something'},
    {en:'periodic',jp:'happening regularly'}
  ]},
  {name:'LogExp3 動名詞',words:[
    {en:'practice',jp:'S+V+V-ing をとる動詞（練習する）'},
    {en:'enjoy',jp:'S+V+V-ing をとる動詞（楽しむ）'},
    {en:'be used to V-ing',jp:'S+V+V-ing をとる表現（〜することに慣れている）'},
    {en:'mind',jp:'S+V+V-ing をとる動詞（気にする）'},
    {en:'consider',jp:'S+V+V-ing をとる動詞（検討する）'},
    {en:'imagine',jp:'S+V+V-ing をとる動詞（想像する）'},
    {en:'look forward to V-ing',jp:'S+V+V-ing をとる表現（〜するのを楽しみにする）'},
    {en:'stop',jp:'S+V+V-ing をとる動詞（〜するのをやめる） / to V で「〜するために立ち止まる」と意味が変わる'},
    {en:'quit',jp:'S+V+V-ing をとる動詞（やめる）'},
    {en:'give up',jp:'S+V+V-ing をとる動詞（あきらめる）'},
    {en:'finish',jp:'S+V+V-ing をとる動詞（終える）'},
    {en:'miss',jp:'S+V+V-ing をとる動詞（〜しそこなう・〜しないのが惜しい）'},
    {en:'avoid',jp:'S+V+V-ing をとる動詞（避ける）'},
    {en:'escape',jp:'S+V+V-ing をとる動詞（逃れる）'},
    {en:'help',jp:'S+V+V-ing をとる動詞（避ける／help doing）'},
    {en:'put off',jp:'S+V+V-ing をとる動詞（延期する）'},
    {en:'postpone',jp:'S+V+V-ing をとる動詞（延期する）'},
    {en:'object to V-ing',jp:'S+V+V-ing をとる表現（〜することに反対する）'},
    {en:'be opposed to V-ing',jp:'S+V+V-ing をとる表現（〜することに反対している）'},
    {en:'deny',jp:'S+V+V-ing をとる動詞（否定する）'},
    {en:'resist',jp:'S+V+V-ing をとる動詞（抵抗する）'},
    {en:'remember V-ing',jp:'to V と意味が違う：V-ing＝〜したことを覚えている / to V＝忘れずに〜する'},
    {en:'forget V-ing',jp:'to V と意味が違う：V-ing＝〜したことを忘れる / to V＝〜するのを忘れる'},
    {en:'regret V-ing',jp:'to V と意味が違う：V-ing＝〜したことを後悔する / to V＝残念ながら〜する'},
    {en:'mean V-ing',jp:'to V と意味が違う：V-ing＝〜することを意味する / to V＝〜するつもりである'},
    {en:'try V-ing',jp:'to V と意味が違う：V-ing＝試しに〜してみる / to V＝〜しようとする'},
    {en:'need V-ing',jp:'to V と意味が違う：V-ing＝〜される必要がある（受動的） / to V＝〜する必要がある'},
    {en:'want V-ing',jp:'to V と意味が違う：V-ing＝〜される必要がある（口語的） / to V＝〜したい'}
  ]}
];
