// デフォルト単元データ
// 授業で使う単元を追加・編集してください

// ══ Default units (seeded on first load) ══
const DEFAULTS=[
  {name:'LogExp3 動名詞',words:[
    {en:'practice',jp:'S+V+V-ing をとる動詞（練習する）'},
    {en:'enjoy',jp:'S+V+V-ing をとる動詞（楽しむ）'},
    {en:'be used to V-ing',jp:'S+V+V-ing をとる表現（〜することに慣れている）'},
    {en:'mind',jp:'S+V+V-ing をとる動詞（気にする）'},
    {en:'consider',jp:'S+V+V-ing をとる動詞（検討する）'},
    {en:'imagine',jp:'S+V+V-ing をとる動詞（想像する）'},
    {en:'look forward to V-ing',jp:'S+V+V-ing をとる表現（〜するのを楽しみにする）'},
    {en:'stop',jp:'S+V+V-ing をとる動詞（〜するのをやめる） / to V で「〜するために立ち止まる」と意味が変わる'},
    {en:'quit',jp:'S+V+V-ing をとる動詞（やめる）'},
    {en:'give up',jp:'S+V+V-ing をとる動詞（あきらめる）'},
    {en:'finish',jp:'S+V+V-ing をとる動詞（終える）'},
    {en:'miss',jp:'S+V+V-ing をとる動詞（〜しそこなう・〜しないのが惜しい）'},
    {en:'avoid',jp:'S+V+V-ing をとる動詞（避ける）'},
    {en:'escape',jp:'S+V+V-ing をとる動詞（逃れる）'},
    {en:'help',jp:'S+V+V-ing をとる動詞（避ける／help doing）'},
    {en:'put off',jp:'S+V+V-ing をとる動詞（延期する）'},
    {en:'postpone',jp:'S+V+V-ing をとる動詞（延期する）'},
    {en:'object to V-ing',jp:'S+V+V-ing をとる表現（〜することに反対する）'},
    {en:'be opposed to V-ing',jp:'S+V+V-ing をとる表現（〜することに反対している）'},
    {en:'deny',jp:'S+V+V-ing をとる動詞（否定する）'},
    {en:'resist',jp:'S+V+V-ing をとる動詞（抵抗する）'},
    {en:'remember V-ing',jp:'to V と意味が違う：V-ing＝〜したことを覚えている / to V＝忘れずに〜する'},
    {en:'forget V-ing',jp:'to V と意味が違う：V-ing＝〜したことを忘れる / to V＝〜するのを忘れる'},
    {en:'regret V-ing',jp:'to V と意味が違う：V-ing＝〜したことを後悔する / to V＝残念ながら〜する'},
    {en:'mean V-ing',jp:'to V と意味が違う：V-ing＝〜することを意味する / to V＝〜するつもりである'},
    {en:'try V-ing',jp:'to V と意味が違う：V-ing＝試しに〜してみる / to V＝〜しようとする'},
    {en:'need V-ing',jp:'to V と意味が違う：V-ing＝〜される必要がある（受動的） / to V＝〜する必要がある'},
    {en:'want V-ing',jp:'to V と意味が違う：V-ing＝〜される必要がある（口語的） / to V＝〜したい'}
  ]},
  {name:'EngExe1 U5',words:[
    {en:'compromise',jp:'妥協、譲歩'},
    {en:'conservation',jp:'保全、保護'},
    {en:'durable',jp:'耐久性のある'},
    {en:'efficiency',jp:'効率、効率性'},
    {en:'relevant',jp:'関連性のある'},
    {en:'secondhand',jp:'中古の、間接的な'},
    {en:'sector',jp:'分野、部門'}
  ]},
  {name:'EngComm3 U5R1 英日',words:[
    {en:'legend',jp:'伝説'},
    {en:'curiously',jp:'不思議なほどに'},
    {en:'massively',jp:'がっしりした'},
    {en:'immense',jp:'はかり知れない'},
    {en:'capture',jp:'…を引きつける'},
    {en:'vanish',jp:'（突然）消える'},
    {en:'extraordinary',jp:'驚くべき，非凡な'},
    {en:'constant',jp:'絶え間なく続く'},
    {en:'factual',jp:'事実に基づく'},
    {en:'flame',jp:'炎'},
    {en:'lord',jp:'君主，領主'},
    {en:'inevitable',jp:'《the～》避けられない運命'},
    {en:'defense',jp:'《通例複数形～s》防御施設，とりで'},
    {en:'sword',jp:'刀'},
    {en:'emerge',jp:'現れる'},
    {en:'confusion',jp:'混乱'},
    {en:'tighten',jp:'しっかり締まる'},
    {en:'rage',jp:'荒れ狂う'},
    {en:'proverb',jp:'ことわざ'},
    {en:'gossip',jp:'うわさ話をする'},
    {en:'literal',jp:'文字どおりの'},
    {en:'barely',jp:'かろうじて'},
    {en:'terrifying',jp:'恐ろしい'},
    {en:'survivor',jp:'生存者'},
    {en:'servant',jp:'使用人，召使'},
    {en:'mission',jp:'任務'},
    {en:'bundle',jp:'束，包み'},
    {en:'urge',jp:'…をせきたてる'},
    {en:'onward',jp:'前方へ，先へ'},
    {en:'heir',jp:'後継者，跡取り'}
  ]},
  {name:'EngComm3 U5R2 英日',words:[
    {en:'cope',jp:'対処する'},
    {en:'unfamiliar',jp:'なじみのない'},
    {en:'empathetic',jp:'人の気持ちの分かる'},
    {en:'initial',jp:'初めの'},
    {en:'surrounding',jp:'《複数形～s》環境，周囲（の状況）'},
    {en:'anxiety',jp:'心配，不安'},
    {en:'symptom',jp:'症状'},
    {en:'characterize',jp:'…を特徴づける'},
    {en:'similarity',jp:'類似点'},
    {en:'phase',jp:'段階，時期'},
    {en:'exhausting',jp:'心身を疲れさせる'},
    {en:'accommodation',jp:'住居，住宅'},
    {en:'adjustment',jp:'適応，順応'},
    {en:'acceptance',jp:'受容，受け入れ'},
    {en:'ashamed',jp:'恥ずかしく思う'},
    {en:'barrier',jp:'障害，障壁'},
    {en:'reality',jp:'現実，事実'}
  ]},
  {name:'EngComm3 U6R1 英日',words:[
    {en:'prohibit',jp:'…を禁止する'},
    {en:'visually',jp:'視覚的に'},
    {en:'impaired',jp:'障害のある'},
    {en:'partially',jp:'部分的に'},
    {en:'typical',jp:'典型的な'},
    {en:'sculpture',jp:'彫刻'},
    {en:'alike',jp:'同じように'},
    {en:'navigate',jp:'…を誘導する'},
    {en:'dimly',jp:'薄暗く'},
    {en:'entire',jp:'全体の，全部の'},
    {en:'assistance',jp:'手助け'},
    {en:'virtually',jp:'コンピュータ上で，仮想的に'},
    {en:'occasionally',jp:'時折，時々'},
    {en:'directly',jp:'直接に'},
    {en:'texture',jp:'手ざわり'},
    {en:'vary',jp:'様々である，異なる'}
  ]},
  {name:'EngComm3 U6R2 英日',words:[
    {en:'accessible',jp:'利用しやすい'},
    {en:'invisible',jp:'見えない'},
    {en:'disable',jp:'…（の機能）を無効にする'},
    {en:'distinguish',jp:'…を区別する'},
    {en:'parenthesis',jp:'《通例複数形parentheses》丸かっこ，パーレン'},
    {en:'external',jp:'外部の'},
    {en:'convert',jp:'…を変換する'},
    {en:'output',jp:'出力（データ）'},
    {en:'otherwise',jp:'さもないと'},
    {en:'equally',jp:'同様に'},
    {en:'flowery',jp:'飾りたてた，美文調の'},
    {en:'plain',jp:'分かりやすい，平易な'},
    {en:'embed',jp:'…を埋め込む'},
    {en:'highlight',jp:'…を強調する'},
    {en:'abbreviation',jp:'略語'},
    {en:'decorative',jp:'装飾用の'},
    {en:'ignorable',jp:'無視できる'}
  ]},
  {name:'EngComm3 U5R1 英英',kind:'enen',words:[
    {en:'legend',jp:"a story from ancient times, usually about brave people, adventures, etc."},
    {en:'curiously',jp:"strangely or in an unusual way"},
    {en:'massively',jp:"heavily and powerfully"},
    {en:'immense',jp:"extremely big in size or degree"},
    {en:'capture',jp:"to catch someone's attention or to make someone interested in something"},
    {en:'vanish',jp:"to disappear, especially in a sudden or mysterious way"},
    {en:'extraordinary',jp:"very unusual, surprising or strange"},
    {en:'constant',jp:"happening all the time"},
    {en:'flame',jp:"a hot, bright stream of burning gas coming from something on fire"},
    {en:'lord',jp:"a powerful man, usually of medieval Europe, who owned a lot of land and property"},
    {en:'inevitable',jp:"something that is sure to happen and cannot be prevented"},
    {en:'defense',jp:"things that are available to protect against enemy attacks"},
    {en:'sword',jp:"a weapon with a long, sharp metal blade and a handle"},
    {en:'emerge',jp:"to appear by coming out of somewhere"},
    {en:'confusion',jp:"a situation that is very difficult to understand or control"},
    {en:'tighten',jp:"to fix something more securely, making it more difficult to move"},
    {en:'rage',jp:"to happen in a violent way"},
    {en:'proverb',jp:"a well-known phrase or statement that gives advice or says something that is commonly true"},
    {en:'gossip',jp:"to talk about the private lives of other people, often in an unkind or untrue way"},
    {en:'literal',jp:"being the most basic or original meaning, usually of a word or phrase"},
    {en:'barely',jp:"just; not more than"},
    {en:'terrifying',jp:"extremely scary"},
    {en:'survivor',jp:"a person who continues to live after coming close to death"},
    {en:'servant',jp:"a person who is employed by someone to cook, clean, etc. for them in their home"},
    {en:'mission',jp:"an important job, especially one that involves the military and travelling"},
    {en:'bundle',jp:"a group of things, such as papers or clothes, that are tied together"},
    {en:'urge',jp:"to strongly advise someone to do something"},
    {en:'onward',jp:"continuing to move forward"},
    {en:'heir',jp:"a person with the legal right to receive someone's property, money, etc., when they die"}
  ]},
  {name:'EngComm3 U6R1 英英',kind:'enen',words:[
    {en:'prohibit',jp:"to officially stop something from being done"},
    {en:'visually',jp:"related to seeing or sight"},
    {en:'impaired',jp:"not working as well as it should"},
    {en:'partially',jp:"not completely"},
    {en:'typical',jp:"having the qualities or features that are usual for a certain group or thing"},
    {en:'sculpture',jp:"an object made by carving or shaping wood, stone, clay, etc., usually by an artist"},
    {en:'alike',jp:"in a similar way"},
    {en:'navigate',jp:"to direct the course of something such as a ship or plane"},
    {en:'dimly',jp:"in a way that is not very bright or clear"},
    {en:'entire',jp:"including every part of something"},
    {en:'assistance',jp:"help or support"},
    {en:'virtually',jp:"on a computer and not involving the real world"},
    {en:'occasionally',jp:"sometimes but not often or on a regular basis"},
    {en:'directly',jp:"with nothing or no one coming in between"},
    {en:'texture',jp:"the way something feels when you touch it"},
    {en:'vary',jp:"to be different from each other"}
  ]},
  {name:'EngExe1 U6-1',words:[
    {en:'biomass energy',jp:'バイオマスエネルギー'},
    {en:'geothermal energy',jp:'地熱エネルギー'},
    {en:'hydropower',jp:'水力発電'},
    {en:'solar power',jp:'太陽光発電'},
    {en:'wind power',jp:'風力発電'},
    {en:'aquatic',jp:'水生の、水中の'},
    {en:'offshore',jp:'沖合の、海上の'},
    {en:'inexhaustible',jp:'尽きることのない、無尽蔵の'},
    {en:'initial',jp:'初めの、最初の'},
    {en:'generate',jp:'（電力・エネルギーなどを）発生させる、生み出す'},
    {en:'universal',jp:'普遍的な、万人共通の'},
    {en:'utilize',jp:'…を利用する、活用する'}
  ]}
];
