const DEFAULTS = [
  {
    name: 'EngComm3 U3R1 英日',
    words: [
      {en:'universality',jp:'普遍性'},
      {en:'organism',jp:'生物、有機体'},
      {en:'assumption',jp:'仮定、思い込み'},
      {en:'impose',jp:'課す、押し付ける'},
      {en:'exaggerated',jp:'誇張された'},
      {en:'chronological',jp:'年代順の、時系列の'},
      {en:'clarity',jp:'明瞭さ、明確さ'},
      {en:'repetition',jp:'繰り返し'},
      {en:'arise',jp:'生じる、起こる'},
      {en:'punish',jp:'罰する'},
      {en:'reward',jp:'報いる、褒美を与える'},
      {en:'individualistic',jp:'個人主義的な'},
      {en:'bravery',jp:'勇敢さ'},
      {en:'determination',jp:'決意'},
      {en:'emulate',jp:'見習う、まねる'},
      {en:'migration',jp:'移住、移動'}
    ]
  },

  {
    name: 'EngComm3 U3R2 英日',
    words: [
      {en:'refuse',jp:'断る'},
      {en:'bang',jp:'バンと音を立てる'},
      {en:'scratch',jp:'ひっかく'},
      {en:'nearby',jp:'近くの'},
      {en:'armful',jp:'ひとかかえ'},
      {en:'stir',jp:'かき混ぜる'},
      {en:'dip',jp:'浸す'},
      {en:'magnificent',jp:'壮大な、見事な'},
      {en:'gladly',jp:'喜んで'},
      {en:'townsfolk',jp:'町の人々'},
      {en:'edge',jp:'端、縁'},
      {en:'feast',jp:'ごちそう、宴会'},
      {en:'repay',jp:'恩返しをする、返済する'},
      {en:'tug',jp:'ぐいと引く'}
    ]
  },

  {
    name: 'EngComm3 U4R1 英日',
    words: [
      {en:'astonishing',jp:'驚くべき'},
      {en:'confirm',jp:'確認する'},
      {en:'exceptionally',jp:'並外れて、非常に'},
      {en:'volcanic',jp:'火山の'},
      {en:'disaster',jp:'災害'},
      {en:'wealthy',jp:'裕福な'},
      {en:'eruption',jp:'噴火'},
      {en:'invaluable',jp:'非常に貴重な'},
      {en:'excavation',jp:'発掘'},
      {en:'literally',jp:'文字どおりに'},
      {en:'considerably',jp:'かなり'},
      {en:'vibrant',jp:'活気のある'},
      {en:'facade',jp:'正面、外観'},
      {en:'mythical',jp:'神話上の'},
      {en:'speculate',jp:'推測する'},
      {en:'modify',jp:'修正する'},
      {en:'purposely',jp:'故意に'}
    ]
  },

  {
    name: 'EngComm3 U4R2 英日',
    words: [
      {en:'civilization',jp:'文明'},
      {en:'intentionally',jp:'故意に'},
      {en:'tomb',jp:'墓'},
      {en:'basement',jp:'地下室'},
      {en:'seal',jp:'封印する'},
      {en:'solid',jp:'固体の、頑丈な'},
      {en:'propose',jp:'提案する'},
      {en:'current',jp:'現在の'},
      {en:'engaged',jp:'従事している'},
      {en:'headquarters',jp:'本部'},
      {en:'controversy',jp:'論争'},
      {en:'harsh',jp:'厳しい'},
      {en:'artifact',jp:'工芸品、人工遺物'},
      {en:'authority',jp:'権威、当局'}
    ]
  },

  {
    name: 'EngComm3 U3R1 英英',
    words: [
      {en:'universal',jp:'true or correct in every situation'},
      {en:'familiarity',jp:'a good knowledge of something such as a place or subject'},
      {en:'cape',jp:'a loose coat with no sleeves that is fastened around the neck and hangs from the shoulders'},
      {en:'panther',jp:'a large, typically black wild animal of the cat family'},
      {en:'goat',jp:'an animal, usually with horns and a beard, that lives wild in the mountains or is kept as a farm animal'},
      {en:'universality',jp:'the state of existing everywhere or involving everyone'},
      {en:'echo',jp:'to continue to be discussed and remain important'},
      {en:'distant',jp:'far off in space or time'},
      {en:'anthropologist',jp:'a person who studies the human race, societies, cultures, etc.'},
      {en:'biological',jp:'related to the natural processes of living things'},
      {en:'organism',jp:'any living thing, such as an animal, plant or human'},
      {en:'finding',jp:'a piece of information discovered during research'},
      {en:'origin',jp:'a thing where something comes from, or a place where something begins'},
      {en:'particular',jp:'special; used to say that you mean one thing'},
      {en:'inclusion',jp:'the fact of being part of something'},
      {en:'originally',jp:'existing from the beginning'},
      {en:'assumption',jp:'something that you think is true but have no proof for'},
      {en:'theory',jp:'an idea that is believed to be true but has not yet been proved'},
      {en:'impose',jp:'to force someone to accept the same ideas, opinions, etc. as you'},
      {en:'trait',jp:'a certain quality in someone\'s personality'},
      {en:'setting',jp:'the place and time where events happen in films, books, plays, etc.'},
      {en:'rarely',jp:'hardly ever'},
      {en:'one-dimensional',jp:'too simple and therefore boring and shallow'},
      {en:'exaggerated',jp:'appearing larger, better, worse, etc. than it really is'},
      {en:'utterly',jp:'completely; usually used to stress that something is bad or that a feeling is strong'},
      {en:'pure',jp:'totally good or clean'},
      {en:'chronological',jp:'arranged in the order of which things happened'},
      {en:'clarity',jp:'the quality of being easily understood'},
      {en:'repetition',jp:'doing or saying the same thing over and over again'},
      {en:'plot',jp:'the events that form the story of a book, play or film'},
      {en:'aspect',jp:'one part of something that has many parts, such as an idea, situation or problem'},
      {en:'teller',jp:'a person who narrates a story'},
      {en:'arise',jp:'to begin or happen'},
      {en:'format',jp:'the way in which something is arranged'},
      {en:'giraffe',jp:'a tall African animal with a long neck and spotted fur'},
      {en:'cumulative',jp:'increasing by things being added one after another'},
      {en:'magical',jp:'relating to magic; mysterious'},
      {en:'satisfied',jp:'pleased that an achievement has been made or something has gone as desired'},
      {en:'punish',jp:'to cause someone to suffer because they have done something wrong or have broken the law'},
      {en:'failing',jp:'a flaw or weakness'},
      {en:'reward',jp:'to give someone something for doing something helpful'},
      {en:'individualistic',jp:'relating to someone who is unique'},
      {en:'rely',jp:'to need something or someone in order to live or work properly'},
      {en:'bravery',jp:'behavior that shows courage'},
      {en:'cunning',jp:'the skill of being clever to get what you want, especially by tricking other people'},
      {en:'determination',jp:'the ability to keep trying to do something even though it is difficult'},
      {en:'emulate',jp:'to try to do something in the same way as someone else, especially because you want to be like them'},
      {en:'prize',jp:'to think that someone or something has great value and importance'},
      {en:'migration',jp:'when large numbers of people move to another region or country, especially to find a better life'}
    ]
  },

  {
    name:'EngComm3 U4R1 英英',
    words:[
      {en:'Italy',jp:'a country in southern Europe'},
      {en:'fast-food',jp:'related to food, such as hamburgers and French fries, that is served quickly and can be taken out'},
      {en:'counter',jp:'a long, flat surface, usually in a shop, bank or restaurant, at which people are served'},
      {en:'unearth',jp:'to find something in the ground, usually by digging'},
      {en:'snack bar',jp:'an informal restaurant where you can buy snacks or small meals'},
      {en:'excavate',jp:'to dig carefully in the ground to look for things such as ancient objects'},
      {en:'uncover',jp:'to discover something that was hidden'},
      {en:'astonishing',jp:'extremely surprising'},
      {en:'confirm',jp:'to prove that something is true'},
      {en:'tasty',jp:'having a strong and pleasant flavor'},
      {en:'multi-sided',jp:'involving various aspects or ideas'},
      {en:'thermopolium',jp:'places in ancient Rome where food and hot drinks were sold'},
      {en:'exceptionally',jp:'in a way that is extreme'},
      {en:'volcanic',jp:'relating to or made by a volcano'},
      {en:'ash',jp:'the soft gray or black powder that is left after something has burned'},
      {en:'A.D.',jp:'used after a date to show that it was after Christ was born'},
      {en:'erupt',jp:'to explode, sending rocks, smoke, fire, etc. into the air, especially when referring to a volcano'},
      {en:'disaster',jp:'an unexpected event that causes great damage'},
      {en:'bustling',jp:'full of people and busy with activity'},
      {en:'wealthy',jp:'rich; owning a lot of things'},
      {en:'eruption',jp:'the moment when a volcano explodes'},
      {en:'liken',jp:'to point out that two things or people are similar'},
      {en:'invaluable',jp:'so useful that it cannot be replaced'},
      {en:'excavation',jp:'the act of digging carefully in the ground to look for things such as ancient objects'},
      {en:'literally',jp:'using the original meaning of a word or expression'},
      {en:'considerably',jp:'much or plenty of'},
      {en:'serving',jp:'used when giving out food'},
      {en:'decorate',jp:'to add things to something or some place to make it look more attractive'},
      {en:'vibrant',jp:'bright and strong, usually said of colors'},
      {en:'fresco',jp:'a picture painted on a wall while the plaster is still wet'},
      {en:'facade',jp:'the front part of a building'},
      {en:'amazingly',jp:'in a surprising and unbelievable way'},
      {en:'mythical',jp:'existing only in ancient stories'},
      {en:'seahorse',jp:'a small, vertically swimming fish with a head and neck that look like a horse\'s'},
      {en:'gladiator',jp:'a soldier of ancient Rome who was trained to fight men or animals to entertain the public'},
      {en:'rooster',jp:'a male chicken that is an adult'},
      {en:'leash',jp:'a piece of leather, chain, etc., attached to a collar for holding and controlling the wearer'},
      {en:'speculate',jp:'to guess the possible answers to a question without having all the facts and details'},
      {en:'depiction',jp:'the way in which something is shown'},
      {en:'examination',jp:'the act of looking at something carefully'},
      {en:'earthenware',jp:'made of hard baked clay, usually by hand'},
      {en:'supposition',jp:'something you think is true although you are not able to prove it'},
      {en:'snail',jp:'a small, soft creature with a hard shell on its back that moves very slowly'},
      {en:'jar',jp:'a container made of clay, glass, etc. with a wide mouth, usually used to store food'},
      {en:'nutrient-rich',jp:'said of foods that are low in sugar, starches, salt and bad fats, and have plenty of vitamins and minerals'},
      {en:'export',jp:'to sell goods to a foreign country'},
      {en:'economy',jp:'the system of production, trade and money used by a country or region'},
      {en:'crush',jp:'to press something so hard that it is damaged, injured or its shape destroyed'},
      {en:'fava bean',jp:'a large, pale green bean which is grown for food'},
      {en:'modify',jp:'to change something slightly, especially to improve it'},
      {en:'reminder',jp:'something that helps someone remember something'},
      {en:'purposely',jp:'consciously'}
    ]
  }
];