// デフォルト単元データ
// 授業で使う単元を追加・編集してください

// ══ Default units (seeded on first load) ══
const DEFAULTS=[
  {name:'LogExp3 動名詞',words:[
    {en:'practice',jp:'S+V+V-ing をとる動詞（練習する）'},
    {en:'enjoy',jp:'S+V+V-ing をとる動詞（楽しむ）'},
    {en:'be used to V-ing',jp:'S+V+V-ing をとる表現（〜することに慣れている）'},
    {en:'mind',jp:'S+V+V-ing をとる動詞（気にする）'},
    {en:'consider',jp:'S+V+V-ing をとる動詞（検討する）'},
    {en:'imagine',jp:'S+V+V-ing をとる動詞（想像する）'},
    {en:'look forward to V-ing',jp:'S+V+V-ing をとる表現（〜するのを楽しみにする）'},
    {en:'stop',jp:'S+V+V-ing をとる動詞（〜するのをやめる） / to V で「〜するために立ち止まる」と意味が変わる'},
    {en:'quit',jp:'S+V+V-ing をとる動詞（やめる）'},
    {en:'give up',jp:'S+V+V-ing をとる動詞（あきらめる）'},
    {en:'finish',jp:'S+V+V-ing をとる動詞（終える）'},
    {en:'miss',jp:'S+V+V-ing をとる動詞（〜しそこなう・〜しないのが惜しい）'},
    {en:'avoid',jp:'S+V+V-ing をとる動詞（避ける）'},
    {en:'escape',jp:'S+V+V-ing をとる動詞（逃れる）'},
    {en:'help',jp:'S+V+V-ing をとる動詞（避ける／help doing）'},
    {en:'put off',jp:'S+V+V-ing をとる動詞（延期する）'},
    {en:'postpone',jp:'S+V+V-ing をとる動詞（延期する）'},
    {en:'object to V-ing',jp:'S+V+V-ing をとる表現（〜することに反対する）'},
    {en:'be opposed to V-ing',jp:'S+V+V-ing をとる表現（〜することに反対している）'},
    {en:'deny',jp:'S+V+V-ing をとる動詞（否定する）'},
    {en:'resist',jp:'S+V+V-ing をとる動詞（抵抗する）'},
    {en:'remember V-ing',jp:'to V と意味が違う：V-ing＝〜したことを覚えている / to V＝忘れずに〜する'},
    {en:'forget V-ing',jp:'to V と意味が違う：V-ing＝〜したことを忘れる / to V＝〜するのを忘れる'},
    {en:'regret V-ing',jp:'to V と意味が違う：V-ing＝〜したことを後悔する / to V＝残念ながら〜する'},
    {en:'mean V-ing',jp:'to V と意味が違う：V-ing＝〜することを意味する / to V＝〜するつもりである'},
    {en:'try V-ing',jp:'to V と意味が違う：V-ing＝試しに〜してみる / to V＝〜しようとする'},
    {en:'need V-ing',jp:'to V と意味が違う：V-ing＝〜される必要がある（受動的） / to V＝〜する必要がある'},
    {en:'want V-ing',jp:'to V と意味が違う：V-ing＝〜される必要がある（口語的） / to V＝〜したい'}
  ]},
  {name:'EngExe1 U5-1',words:[
    {en:'compromise',jp:'妥協、譲歩'},
    {en:'conservation',jp:'保全、保護'},
    {en:'durable',jp:'耐久性のある'},
    {en:'efficiency',jp:'効率、効率性'},
    {en:'relevant',jp:'関連性のある'},
    {en:'secondhand',jp:'中古の、間接的な'},
    {en:'sector',jp:'分野、部門'}
  ]},
  {name:'EngComm3 U5R1 英日',words:[
    {en:'legend',jp:'伝説'},
    {en:'curiously',jp:'不思議なほどに'},
    {en:'massively',jp:'がっしりした'},
    {en:'immense',jp:'はかり知れない'},
    {en:'capture',jp:'…を引きつける'},
    {en:'vanish',jp:'（突然）消える'},
    {en:'extraordinary',jp:'驚くべき，非凡な'},
    {en:'constant',jp:'絶え間なく続く'},
    {en:'factual',jp:'事実に基づく'},
    {en:'flame',jp:'炎'},
    {en:'lord',jp:'君主，領主'},
    {en:'inevitable',jp:'《the～》避けられない運命'},
    {en:'defense',jp:'《通例複数形～s》防御施設，とりで'},
    {en:'sword',jp:'刀'},
    {en:'emerge',jp:'現れる'},
    {en:'confusion',jp:'混乱'},
    {en:'tighten',jp:'しっかり締まる'},
    {en:'rage',jp:'荒れ狂う'},
    {en:'proverb',jp:'ことわざ'},
    {en:'gossip',jp:'うわさ話をする'},
    {en:'literal',jp:'文字どおりの'},
    {en:'barely',jp:'かろうじて'},
    {en:'terrifying',jp:'恐ろしい'},
    {en:'survivor',jp:'生存者'},
    {en:'servant',jp:'使用人，召使'},
    {en:'mission',jp:'任務'},
    {en:'bundle',jp:'束，包み'},
    {en:'urge',jp:'…をせきたてる'},
    {en:'onward',jp:'前方へ，先へ'},
    {en:'heir',jp:'後継者，跡取り'}
  ]},
  {name:'EngComm3 U5R2 英日',words:[
    {en:'cope',jp:'対処する'},
    {en:'unfamiliar',jp:'なじみのない'},
    {en:'empathetic',jp:'人の気持ちの分かる'},
    {en:'initial',jp:'初めの'},
    {en:'surrounding',jp:'《複数形～s》環境，周囲（の状況）'},
    {en:'anxiety',jp:'心配，不安'},
    {en:'symptom',jp:'症状'},
    {en:'characterize',jp:'…を特徴づける'},
    {en:'similarity',jp:'類似点'},
    {en:'phase',jp:'段階，時期'},
    {en:'exhausting',jp:'心身を疲れさせる'},
    {en:'accommodation',jp:'住居，住宅'},
    {en:'adjustment',jp:'適応，順応'},
    {en:'acceptance',jp:'受容，受け入れ'},
    {en:'ashamed',jp:'恥ずかしく思う'},
    {en:'barrier',jp:'障害，障壁'},
    {en:'reality',jp:'現実，事実'}
  ]},
  {name:'EngComm3 U6R1 英日',words:[
    {en:'prohibit',jp:'…を禁止する'},
    {en:'visually',jp:'視覚的に'},
    {en:'impaired',jp:'障害のある'},
    {en:'partially',jp:'部分的に'},
    {en:'typical',jp:'典型的な'},
    {en:'sculpture',jp:'彫刻'},
    {en:'alike',jp:'同じように'},
    {en:'navigate',jp:'…を誘導する'},
    {en:'dimly',jp:'薄暗く'},
    {en:'entire',jp:'全体の，全部の'},
    {en:'assistance',jp:'手助け'},
    {en:'virtually',jp:'コンピュータ上で，仮想的に'},
    {en:'occasionally',jp:'時折，時々'},
    {en:'directly',jp:'直接に'},
    {en:'texture',jp:'手ざわり'},
    {en:'vary',jp:'様々である，異なる'}
  ]},
  {name:'EngComm3 U6R2 英日',words:[
    {en:'accessible',jp:'利用しやすい'},
    {en:'invisible',jp:'見えない'},
    {en:'disable',jp:'…（の機能）を無効にする'},
    {en:'distinguish',jp:'…を区別する'},
    {en:'parenthesis',jp:'《通例複数形parentheses》丸かっこ，パーレン'},
    {en:'external',jp:'外部の'},
    {en:'convert',jp:'…を変換する'},
    {en:'output',jp:'出力（データ）'},
    {en:'otherwise',jp:'さもないと'},
    {en:'equally',jp:'同様に'},
    {en:'flowery',jp:'飾りたてた，美文調の'},
    {en:'plain',jp:'分かりやすい，平易な'},
    {en:'embed',jp:'…を埋め込む'},
    {en:'highlight',jp:'…を強調する'},
    {en:'abbreviation',jp:'略語'},
    {en:'decorative',jp:'装飾用の'},
    {en:'ignorable',jp:'無視できる'}
  ]},
  {name:'EngComm3 U5R1 英英',kind:'enen',words:[
    {en:'samurai',jp:"a person who belongs to a powerful military class in Japan, usually said of someone in the past"},
    {en:'legend',jp:"a story from ancient times, usually about brave people, adventures, etc."},
    {en:'foreign-born',jp:"born in a foreign country"},
    {en:'Portuguese',jp:"relating to Portugal"},
    {en:'curiously',jp:"strangely or in an unusual way"},
    {en:'massively',jp:"heavily and powerfully"},
    {en:'built',jp:"used to describe a person's size or shape"},
    {en:'bodyguard',jp:"a person whose job is to protect an important person"},
    {en:'immense',jp:"extremely big in size or degree"},
    {en:'capture',jp:"to catch someone's attention or to make someone interested in something"},
    {en:'warlord',jp:"the leader of an unofficial military group that fights against other groups within a certain area"},
    {en:'vanish',jp:"to disappear, especially in a sudden or mysterious way"},
    {en:'excite',jp:"to make someone feel happy, interested, etc., especially about something that is about to happen"},
    {en:'little-known',jp:"known by few people"},
    {en:'gripping',jp:"so exciting or interesting that it keeps your attention"},
    {en:'extraordinary',jp:"very unusual, surprising or strange"},
    {en:'bookworm',jp:"a person who likes to read and reads a lot"},
    {en:'well-written',jp:"written in an interesting and effective way"},
    {en:'nonfiction',jp:"written material that is about real facts and events"},
    {en:'constant',jp:"happening all the time"},
    {en:'Spain',jp:"a country in southwest Europe"},
    {en:'prelude',jp:"something that comes before the main part of a book, event, etc. and serves as a kind of introduction"},
    {en:'daybreak',jp:"the time of day when the sun first appears"},
    {en:'glow',jp:"to produce a soft, steady light"},
    {en:'flame',jp:"a hot, bright stream of burning gas coming from something on fire"},
    {en:'engulf',jp:"to surround or cover something or someone completely"},
    {en:'crimson',jp:"a deep red color"},
    {en:'scatter',jp:"to throw or drop things randomly"},
    {en:'half-dozen',jp:"half of a dozen; a group of or around six things"},
    {en:'crackle',jp:"to make short, sharp sounds like something is burning in a fire"},
    {en:'spark',jp:"to send off small flashes of fire or electricity"},
    {en:'bonfire',jp:"a large fire burned outdoors to burn waste or to celebrate something"},
    {en:'lord',jp:"a powerful man, usually of medieval Europe, who owned a lot of land and property"},
    {en:'entourage',jp:"a group of people who travel or work with an important person"},
    {en:'inevitable',jp:"something that is sure to happen and cannot be prevented"},
    {en:'outnumber',jp:"to be greater in number than someone or something"},
    {en:'gunman',jp:"a man who has and uses a gun, especially to steal from or harm people"},
    {en:'archer',jp:"a person who shoots arrows using a bow"},
    {en:'defense',jp:"things that are available to protect against enemy attacks"},
    {en:'gunfire',jp:"the repeated shooting of guns or the sound made by it"},
    {en:'pause',jp:"to stop doing something for a short time"},
    {en:'traitor',jp:"a person who betrays their country, beliefs, etc."},
    {en:'veteran',jp:"having experience in something, especially as a soldier"},
    {en:'wield',jp:"to hold a weapon or tool as if you are ready to use it"},
    {en:'sword',jp:"a weapon with a long, sharp metal blade and a handle"},
    {en:'spear',jp:"a weapon with a long wooden handle and a sharp metal point, used as a weapon or for hunting"},
    {en:'vengeful',jp:"showing a strong desire to punish someone for doing something bad"},
    {en:'retribution',jp:"severe punishment for serious wrongdoing"},
    {en:'emerge',jp:"to appear by coming out of somewhere"},
    {en:'inferno',jp:"a very large and dangerous fire, usually out of control"},
    {en:'confusion',jp:"a situation that is very difficult to understand or control"},
    {en:'tighten',jp:"to fix something more securely, making it more difficult to move"},
    {en:'blaze',jp:"a fire with strong, bright flames"},
    {en:'rage',jp:"to happen in a violent way"},
    {en:'proverb',jp:"a well-known phrase or statement that gives advice or says something that is commonly true"},
    {en:'gossip',jp:"to talk about the private lives of other people, often in an unkind or untrue way"},
    {en:'literal',jp:"being the most basic or original meaning, usually of a word or phrase"},
    {en:'traitorous',jp:"betraying your country, friends or beliefs"},
    {en:'helmet',jp:"a strong, hard hat worn to protect the head"},
    {en:'barely',jp:"just; not more than"},
    {en:'half-concealed',jp:"partially hidden"},
    {en:'dark-skinned',jp:"having dark-colored skin"},
    {en:'freshly',jp:"recently done, made, prepared, etc."},
    {en:'smear',jp:"to spread a soft substance over a surface, especially in a careless way"},
    {en:'battle',jp:"a fight between groups of people such as armies, especially during a war"},
    {en:'terrifying',jp:"extremely scary"},
    {en:'daunting',jp:"making someone feel slightly scared or worried about their ability to do something"},
    {en:'clutch',jp:"to hold tightly"},
    {en:'blade',jp:"the flat, sharp part of a tool or weapon used for cutting"},
    {en:'lacquer',jp:"to paint wood or metal with a special liquid to form a hard, shiny surface"},
    {en:'vanquish',jp:"to defeat an enemy or opponent completely"},
    {en:'foe',jp:"an enemy"},
    {en:'mortally',jp:"in a way that causes death"},
    {en:'survivor',jp:"a person who continues to live after coming close to death"},
    {en:'cower',jp:"to lower your head and body because you are scared"},
    {en:'maiden',jp:"an unmarried girl or young woman"},
    {en:'flee',jp:"to leave very quickly, especially to escape danger"},
    {en:'servant',jp:"a person who is employed by someone to cook, clean, etc. for them in their home"},
    {en:'loom',jp:"to appear as a large, unclear shape, especially in a scary way"},
    {en:'undaunted',jp:"still willing to continue in spite of difficulties, danger, etc."},
    {en:'wrathful',jp:"feeling very strong anger"},
    {en:'trembling',jp:"shaking slightly and uncontrollably, especially because you are nervous, scared, etc."},
    {en:'fell',jp:"to knock someone or something down"},
    {en:'grimly',jp:"in a serious or sad way, sometimes used to express pleasure or amusement in an unpleasant situation"},
    {en:'much-needed',jp:"long-awaited"},
    {en:'ally',jp:"someone or something that gives support"},
    {en:'mission',jp:"an important job, especially one that involves the military and travelling"},
    {en:'bundle',jp:"a group of things, such as papers or clothes, that are tied together"},
    {en:'cinch',jp:"to fasten a belt, strap, etc. tightly around something"},
    {en:'hip',jp:"the part on each side of the body between the top of the leg and the waist"},
    {en:'thigh',jp:"the part of the leg between the knee and the hip"},
    {en:'urge',jp:"to strongly advise someone to do something"},
    {en:'onward',jp:"continuing to move forward"},
    {en:'mortal remains',jp:"a person's body after they have died"},
    {en:'heir',jp:"a person with the legal right to receive someone's property, money, etc., when they die"},
    {en:'spellbound',jp:"having your attention held completely by something, making it impossible to think about something else"}
  ]},
  {name:'EngComm3 U6R1 英英',kind:'enen',words:[
    {en:'prohibit',jp:"to officially stop something from being done"},
    {en:'visually',jp:"related to seeing or sight"},
    {en:'impaired',jp:"not working as well as it should"},
    {en:'duo',jp:"two people who perform together or are thought of as a pair"},
    {en:'partially',jp:"not completely"},
    {en:'sculpt',jp:"to create a certain shape by carving or shaping wood, stone, clay, etc."},
    {en:'artwork',jp:"objects, such as paintings and sculptures, created by artists"},
    {en:'typical',jp:"having the qualities or features that are usual for a certain group or thing"},
    {en:'sculpture',jp:"an object made by carving or shaping wood, stone, clay, etc., usually by an artist"},
    {en:'alike',jp:"in a similar way"},
    {en:'navigate',jp:"to direct the course of something such as a ship or plane"},
    {en:'dimly',jp:"in a way that is not very bright or clear"},
    {en:'entire',jp:"including every part of something"},
    {en:'assistance',jp:"help or support"},
    {en:'haptic',jp:"relating to the sense of touch"},
    {en:'virtual reality',jp:"an environment created by a computer that seems real to the person interacting with it"},
    {en:'virtually',jp:"on a computer and not involving the real world"},
    {en:'occasionally',jp:"sometimes but not often or on a regular basis"},
    {en:'low tech',jp:"not using the latest technology or methods"},
    {en:'directly',jp:"with nothing or no one coming in between"},
    {en:'texture',jp:"the way something feels when you touch it"},
    {en:'on-site',jp:"at the place where something is happening, such as an event"},
    {en:'vary',jp:"to be different from each other"}
  ]}
];
